# Generated by Django 5.1.2 on 2024-11-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform_alter_flan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flan',
            name='flan_uuid',
        ),
        migrations.RemoveField(
            model_name='flan',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='flan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flan',
            name='slug',
        ),
        migrations.AddField(
            model_name='flan',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='nuevo_atributo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
